HW_3
VolodymyrKM/Python-Enchantress pull request #3
Opened 2021-01-15 08:30 UTC by VolodymyrKM

2021-01-19 14:38 UTC, dimigor requested changes

2021-01-19 14:38 UTC, dimigor commented on homework/test_simple_employee.py
> +# print(emp.monthly_schedule('June'))
якщо коментуєш код, то він навряд колись знадобиться
видаляй з комітів коментований код

2021-01-19 14:38 UTC, dimigor commented on homework/test_test_simple_calc.py
> +        self.assertEqual(add(*inputs), expect)
додай випадки в яких може бути помилка, наприклад ділення на 0б передача інших типів даних

2021-01-19 14:38 UTC, dimigor commented on homework/test_test_simple_employee.py
> +    unittest.main()
не забувай про ендлайн

2021-01-19 14:38 UTC, dimigor commented on homework/test_test_simple_employee.py
> +
два порожніх рядки має бути

2021-01-25 19:03 UTC, VolodymyrKM commented
Ділення на нуль я передав в попередньому варіанті. Додав інший тип даних стр. Та виправив ендлайни.

2021-01-26 08:42 UTC, merged